name: rejuvbridge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - umap-learn
      - hydra-core
      - pyarrow
      - pytest
channels:
  - conda-forge
  - defaults
